import { describe, expect, it } from 'vitest'
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadPet } from '../src/renderer/codex-pet/PetLoader'
import { sliceFrame } from '../src/renderer/FrameDecoder'

const petsDir = fileURLToPath(new URL('../assets/pets/', import.meta.url))

/**
 * End-to-end check that the bundled placeholder pets (generated by
 * `scripts/generate-assets.mjs`) satisfy the Codex contract and decode to
 * sliceable frames. Skipped when assets have not been generated.
 */
describe('bundled placeholder pets (integration)', () => {
  it('decodes and slices a frame for each bundled pet', async () => {
    const blobDir = join(petsDir, 'blob')
    if (!existsSync(join(blobDir, 'spritesheet.webp'))) {
      // eslint-disable-next-line no-console
      console.warn('skipping: assets not generated (run pnpm gen:assets)')
      return
    }

    for (const id of ['blob', 'coral', 'sky', 'text']) {
      const dir = join(petsDir, id)
      const loaded = await loadPet({ directory: dir })
      expect(loaded.manifest.id).toBe(`dsh-${id}`)
      expect(loaded.version).toBe(1)
      expect(loaded.atlasWidth).toBe(1536)
      expect(loaded.atlasHeight).toBe(1872)

      const frame = sliceFrame(
        { width: loaded.atlasWidth, height: loaded.atlasHeight, rgba: loaded.rgba },
        'idle',
        0,
      )
      expect(frame.width).toBe(192)
      expect(frame.height).toBe(208)
      // The placeholder is mostly transparent; assert at least one opaque
      // pixel exists (the body is drawn with alpha 255).
      let opaque = 0
      for (let i = 3; i < frame.rgba.length; i += 4) {
        if (frame.rgba[i] !== 0) opaque++
      }
      expect(opaque).toBeGreaterThan(100)
    }
  })
})
