import { describe, expect, it } from 'vitest'
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadPet } from '../src/renderer/codex-pet/PetLoader'
import { sliceFrame } from '../src/renderer/FrameDecoder'

const petsDir = fileURLToPath(new URL('../assets/pets/', import.meta.url))

/**
 * End-to-end check that the bundled placeholder pet (generated by
 * `scripts/generate-assets.mjs`) satisfies the Codex contract and decodes to
 * sliceable frames. Skipped when assets have not been generated.
 */
describe('bundled placeholder pet (integration)', () => {
  it('decodes and slices a frame for the bundled text pet', async () => {
    const textDir = join(petsDir, 'text')
    if (!existsSync(join(textDir, 'spritesheet.webp'))) {
      // eslint-disable-next-line no-console
      console.warn('skipping: assets not generated (run pnpm gen:assets)')
      return
    }

    const loaded = await loadPet({ directory: textDir })
    expect(loaded.manifest.id).toBe('text')
    expect(loaded.version).toBe(1)
    expect(loaded.atlasWidth).toBe(1536)
    expect(loaded.atlasHeight).toBe(1872)

    const frame = sliceFrame(
      { width: loaded.atlasWidth, height: loaded.atlasHeight, rgba: loaded.rgba },
      'idle',
      0,
    )
    expect(frame.width).toBe(192)
    expect(frame.height).toBe(208)
    // The text pet fills its cells; assert at least one opaque pixel exists.
    let opaque = 0
    for (let i = 3; i < frame.rgba.length; i += 4) {
      if (frame.rgba[i] !== 0) opaque++
    }
    expect(opaque).toBeGreaterThan(100)
  })
})
